version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'Asia/Seoul'
      USER: '${SAMBA_USERNAME};${SAMBA_PASSWORD}'
      USERID: '${SAMBA_UID}'
      GROUPID: '${SAMBA_GID}'
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      - ${SAMBA_MNT_HOME_DIR}:/mnt/home
      - ${SAMBA_MNT_TIME_MACHINE_DIR}:/mnt/time-machine
    command: -s "home;/mnt/home;yes;no;no;${SAMBA_USERNAME}" -s "time-machine;/mnt/time-machine;yes;no;no;${SAMBA_USERNAME}"
