version: '3'

services:
  traefik:
    image: traefik:v1.7
    container_name: traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/etc/traefik
    ports:
      - 80:80
      - 443:443

