version: '3'

services:
  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: always
    volumes:
      - ${WEBDAV_MNT_DIR}:/var/lib/dav
    environment:
      SERVER_NAMES: ${WEBDAV_DOMAIN}
      USERNAME: ${WEBDAV_USERNAME}
      PASSWORD: ${WEBDAV_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${WEBDAV_DOMAIN}"
      - "traefik.port=80"

networks:
  default:
    external:
      name: traefik_default

