version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${NGINX_DOMAIN}"
      - "traefik.port=80"
      - "traefik.protocol=http"
    restart: always

networks:
  default:
    external:
      name: traefik_default
