version: '3'

services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - NODE_ENV=production
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
    depends_on:
      - db
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${STRAPI_DOMAIN}"
      - "traefik.port=1337"

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    volumes:
      - ./db:/data/db
    restart: always

networks:
  default:
    external:
      name: traefik_default

